spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/d2b
    username: postgres
    password: admin

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always